### ISSUE TITLE
[data-source] cases per country / region

### ISSUE THREAD

**Issue by schliflo** [coverified/data#2]
We need a source for data about the current COVID-19 cases that provides:
- current active cases (or all cases and recovered cases)
- current deaths

Ideally this datasource provides official data for all countries

**Comment by schliflo** [comment]
@johanneshiry regarding your comment about the data source here: https://github.com/coverified/data/issues/5#issuecomment-603895971

I already did some digging there, but I don't think we can use their API (looking at the network tab you can see they have a very proprietary structure of their data).

I just found another site however and they seem to have a pretty clean API: https://www.coronatracker.com/country/de/

Looking at https://api.coronatracker.com/v3/stats/worldometer/country?countryCode=DE I think we can grab the numbers pretty cleanly from there. They even have historical data: https://api.coronatracker.com/v3/analytics/trend/country?countryCode=DE&startDate=2020-03-13&endDate=2020-03-27

**Comment by butcherino** [comment]
Maybe this are interesting sources:
https://www.programmableweb.com/news/apis-to-track-coronavirus-covid-19/review/2020/03/25
https://health-api.com/#documentation
https://ncov2019.live/

**Comment by schliflo** [comment]
> Maybe this are interesting sources:
> https://www.programmableweb.com/news/apis-to-track-coronavirus-covid-19/review/2020/03/25

seems to have some promising results

> https://health-api.com/#documentation

has old/invalid data for me: https://health-api.com/api/v1/covid-19/de/full

> https://ncov2019.live/

has no API

However I found the data repo that is connected to health-api and they seem to have up to date data in CSV format: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports

---

Edit:
There is already a repo that provides the JHU in JSON format: https://github.com/pomber/covid19
And an API that uses these datasets: https://covidapi.info/

**Comment by backtrackbaba** [comment]
Hi, I'm one of the authors of [https://covidapi.info/](https://covidapi.info/). I came across of this and wanted to help you out with using our endpoints.

1) current active cases (or all cases and recovered cases)

    For this, you could check out this endpoint that we recently introduced [`/api/v1/global/latest`](https://covidapi.info/api/v1/global/latest) which gives you the count of all the countries, the date of record and a list of all the date of all the countries. This endpoint has been added a few minutes back. Let me know if you need any minor changes in the structure of the response. I'll be able to do it as users haven't been informed about this yet.
 
2) current deaths

    This, I'm assuming would be a global data point, you could get that by using this endpoint [`/api/v1/global`](https://covidapi.info/api/v1/global) which will give you the global record as per the last date available.

**P.S:** Certain records (usually the latest day) would show 0 for the count fo recovered individuals as JHU, our upstream data provider has changed the data a bit but it's a WIP and once it's rectified over there it'll reflect in our API's too.

Let me know if I could help you in any way.

Hack On!

**Comment by schliflo** [comment]
Hey @backtrackbaba thank you so much for contacting us!

I think we'd be using the `country` endpoint, as we need country specific data.
Playing around with your API I had no problems getting It working - it was very smooth.

The only problem we have is, that we don't really want to use JHU data, as they have a different counting method than the one used by officials in Germany (https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html)
We want to be an official communication channel so we're trying to get RKI data in a machine readable format.

**Comment by backtrackbaba** [comment]
Yes, I agree, locally sourced data is the most reliable one. I just checked out the site and found [this PDF](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/2020-03-26-en.pdf?__blob=publicationFile) and just tried changing in the dates and found other PDF's also found the listing of archives [here](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Archiv.html)

**Comment by backtrackbaba** [comment]
Also, we are working on a v2 of our application where we provide API's sourced from JHU as well as local health authorities. This is still a line of thought

I'll keep you informed if it starts taking shape!

**Comment by schliflo** [comment]
Thank you! It'd be really nice if you'd be able to include RKI sourced data in a future version of your API.
Thank you for keeping in touch!

**Comment by schliflo** [comment]
This is closed for now as we decided to rely on JHU data in the meantime
