### ISSUE TITLE
[data-source] scientific reports / posts & papers

### ISSUE THREAD

**Issue by schliflo** [coverified/data#3]
We need a or multiple sources for data that provides:

- title
- short description
- timestamp
- link

for scientific publications

**Comment by schliflo** [comment]
this twitter feed provides lots of official postings: https://twitter.com/i/events/1235661905152245761

**Comment by schliflo** [comment]
I found https://www.coronatracker.com/country/de/ - they do provide regional news in various languages.
Looking at https://api.coronatracker.com/v3/analytics/trend/country?countryCode=DE&startDate=2020-03-13&endDate=2020-03-27 seems really promising

---

Edit:
They only provide media news, which is out of scope for us as we want to specifically provide governmental or scientific publications only (to avoid credibility issues or conflict of interest).

**Comment by butcherino** [comment]
Maybe this is a interesting source: https://ncov2019.live/

**Comment by schliflo** [comment]
These are some interesting APIs we should take a look at:
- https://www.programmableweb.com/api/springer-open-access-rest-api-v20
- https://www.programmableweb.com/api/smartable-ai-covid-19-stats-and-news-rest-api-v10
- https://www.programmableweb.com/api/aylien-news

**Comment by schliflo** [comment]
Closing as this is solved buy the current RSS fetching solution
