### ISSUE TITLE
Automate data updates

### ISSUE THREAD

**Issue by schliflo** [coverified/data#5]
We can probably use [GitHub Actions](https://github.com/features/actions) to automate the data updates

**Comment by johanneshiry** [comment]
- Do you intend to stick to github as "database"? 
- Are there any information on apis (e.g. from https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4/page/page_0/) available?
- Are we going to stick to json as data structure?

**Comment by schliflo** [comment]
I do not intend to keep this as the database in the long run. however I think this is a good enough and performant solution in the short term while we work to get the database/api up and running.

Data structure is up for debate. My intention is to have a GraphQL or REST based API in the future. So it will probably stay JSON, but the format absolutely can change.

We started with https://sheety.co/ and a Google Doc and the current JSON structure is just a static Version of exactly that, just fyi so you know where the structure comes from.

**Comment by schliflo** [comment]
This is solved via the GitHub Action that was implemented recently
